### ISSUE TITLE
Setting Active Calendar in DateAdapter

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/JDNConvertibleCalendarDateAdapter#22]
The active calendar can be set via an `InjectionToken` (`BehaviorSubject<string>`) now (as suggested in https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/pull/9#discussion_r316888387):

https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/blob/a18f1619d5b7bf26b770827d71b3b8bbef442986/projects/jdnconvertible-calendar-date-adapter/src/lib/jdnconvertible-calendar-date-adapter.ts#L76-L86

Should `getValue` be called before to make absolutely sure that the calendar is set? 

Technically, the active calendar is set via a callback and it's not guaranteed that it's not `undefined` at construction time.

The `BehaviourSubject` is updated via a directive:

https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/blob/a18f1619d5b7bf26b770827d71b3b8bbef442986/src/app/app.component.ts#L139-L158

https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/blob/a18f1619d5b7bf26b770827d71b3b8bbef442986/src/app/app.component.html#L1-L7

So from the directive's input the calendar can be set for the given date.

**Comment by tobiasschweizer** [comment]
@mmalerba I would be glad to get your opinion here.

**Comment by mmalerba** [comment]
Yeah, this sounds like what I was thinking

**Comment by tobiasschweizer** [comment]
> Yeah, this sounds like what I was thinking

Thanks for your reply.

So you think this is not an issue?

> Technically, the active calendar is set via a callback and it's not guaranteed that it's not undefined at construction time.

**Comment by mmalerba** [comment]
I think that's fine as long as you know you won't try to do anything with the value until it is defined (or use some fallback value if it's still undefined at the point where you need it)

**Comment by tobiasschweizer** [comment]
> I think that's fine as long as you know you won't try to do anything with the value until it is defined (or use some fallback value if it's still undefined at the point where you need it)

I think this should not be an issue because the `BehaviourSubject` is initialised with 'Gregorian' (I figured out that I have to use `useFactory` to guarantee that there is always a new `BehaviorSubject` per directive).

https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/blob/a18f1619d5b7bf26b770827d71b3b8bbef442986/src/app/app.component.ts#L134-L146

And the the actual calendar is set via the directive's input using the `ngOnChanges` lifecycle hook:

https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/blob/a18f1619d5b7bf26b770827d71b3b8bbef442986/src/app/app.component.ts#L146-L158

And since the directive is the parent (it wraps the DatePicker), this should all happen **before** the DatePicker is actually instantiated, right?

**Comment by mmalerba** [comment]
Yeah that should be fine, if you try to access it too soon you'll just get 'Gregorian' - so worst case you'll render that and then immediately re-render the correct thing
