### ISSUE TITLE
stackblitz

### ISSUE THREAD

**Issue by amiraziz** [dhlab-basel/JDNConvertibleCalendarDateAdapter#28]
hi 

can you run your project with stackblitz?
you can test it with this url  but your dependencies is not exists in npm repo!

[stackblitz](https://stackblitz.com/github/dhlab-basel/JDNConvertibleCalendarDateAdapter)

**Comment by tobiasschweizer** [comment]
I think it could be related to spelling (hyphens). Could you try `jdnconvertiblecalendardateadapter` (https://www.npmjs.com/package/jdnconvertiblecalendardateadapter)? The latest version is 0.0.16.
